services:
  backend:
    depends_on:
      - db
    build:
      args:
        UID: ${UID:-1000}
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./logs:/app/logs
    environment:
      APP_FRONTEND_ORIGIN: http://localhost:8081,http://192.168.0.152:8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/asz_management_suite
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: asz_management_suite
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8081:80"
    depends_on:
      - backend

volumes:
  pgdata: