spring.application.name=asz-inventory-api

app.frontend.origin=http://localhost:5173

spring.datasource.url=jdbc:postgresql://localhost:5432/asz_management_suite

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true